INSERT INTO roles(name) SELECT 'ROLE_USER' WHERE NOT EXISTS ( SELECT name FROM roles WHERE name = 'ROLE_USER');
INSERT INTO roles(name) SELECT 'ROLE_ADMIN' WHERE NOT EXISTS ( SELECT name FROM roles WHERE name = 'ROLE_ADMIN');

INSERT INTO tags(name) SELECT 'GENERAL' WHERE NOT EXISTS ( SELECT name FROM tags WHERE name = 'GENERAL');
INSERT INTO tags(name) SELECT 'IMPORTANT' WHERE NOT EXISTS ( SELECT name FROM tags WHERE name = 'IMPORTANT');
INSERT INTO tags(name) SELECT 'WORK' WHERE NOT EXISTS ( SELECT name FROM tags WHERE name = 'WORK');
INSERT INTO tags(name) SELECT 'PERSONAL' WHERE NOT EXISTS ( SELECT name FROM tags WHERE name = 'PERSONAL');
INSERT INTO tags(name) SELECT 'OTHER' WHERE NOT EXISTS ( SELECT name FROM tags WHERE name = 'OTHER');